/*
 * AllInOne Banner - Banner With Playlist v3.6.3
 *
 * Copyright 2012-2023, LambertGroup
 *
*/


(function(f){function W(a,b,e){e.responsive&&(newCss="",-1!=a.css("font-size").lastIndexOf("px")?(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(e.origWidth/e.width)+"px;"):-1!=a.css("font-size").lastIndexOf("em")&&(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(e.origWidth/e.width)+"em;"),-1!=a.css("line-height").lastIndexOf("px")?(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("px")),
newCss+="line-height:"+lineHeight/(e.origWidth/e.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),newCss+="line-height:"+lineHeight/(e.origWidth/e.width)+"em;"),a.wrapInner('<div class="newFS" style="'+newCss+'" />'));var k=a.attr("data-final-left"),h=a.attr("data-final-top");e.responsive&&(k=parseInt(k/(e.origWidth/e.width),10),h=parseInt(h/(e.origWidth/e.width),10));e=1;1==b.isVideoPlaying&&(e=0);a.animate({opacity:e,
left:k+"px",top:h+"px"},1E3*a.attr("data-duration"),function(){1==b.isVideoPlaying&&f(b.currentImg.attr("data-text-id")).children().css("opacity",0)})}function Q(a,b,e,k){f(a.currentImg.attr("data-text-id")).css("display","block");e=f(a.currentImg.attr("data-text-id")).children();var h=0;currentText_arr=[];e.each(function(){currentText_arr[h]=f(this);var c=currentText_arr[h].attr("data-initial-left"),t=currentText_arr[h].attr("data-initial-top");b.responsive&&(c=parseInt(c/(b.origWidth/b.width),10),
t=parseInt(t/(b.origWidth/b.width),10));currentText_arr[h].css({left:c+"px",top:t+"px",opacity:parseInt(currentText_arr[h].attr("data-fade-start"),10)/100});var C=currentText_arr[h];setTimeout(function(){W(C,a,b)},1E3*currentText_arr[h].attr("data-delay"));h++})}function X(a){for(var b,e,k=a.length;k;b=parseInt(Math.random()*k,10),e=a[--k],a[k]=a[b],a[b]=e);return a}function R(a,b){nowx=(new Date).getTime();a.mouseOverBanner||a.effectIsRunning||!b.showCircleTimer||(a.ctx.clearRect(0,0,a.canvas.width,
a.canvas.height),a.ctx.beginPath(),a.ctx.globalAlpha=b.behindCircleAlpha/100,a.ctx.arc(b.circleRadius+2*b.circleLineWidth,b.circleRadius+2*b.circleLineWidth,b.circleRadius,0,2*Math.PI,!1),a.ctx.lineWidth=b.circleLineWidth+2,a.ctx.strokeStyle=b.behindCircleColor,a.ctx.stroke(),a.ctx.beginPath(),a.ctx.globalAlpha=b.circleAlpha/100,a.ctx.arc(b.circleRadius+2*b.circleLineWidth,b.circleRadius+2*b.circleLineWidth,b.circleRadius,0,(a.timeElapsed+nowx-a.arcInitialTime)/1E3*2/b.autoPlay*Math.PI,!1),a.ctx.lineWidth=
b.circleLineWidth,a.ctx.strokeStyle=b.circleColor,a.ctx.stroke())}function S(a,b,e){var k=G();f(".stripe",a).remove();f(".block",a).remove();J=F=Math.round(a.width()/b.numberOfStripes);for(var h=!0,c=0;c<b.numberOfStripes;c++)c==b.numberOfStripes-1&&(J=a.width()-F*(b.numberOfStripes-1)),!b.responsive||-1==k||-1!=k&&9<=k?-1!=w.indexOf("ipad")||-1!=w.indexOf("iphone")||-1!=w.indexOf("ipod")||-1!=w.indexOf("webos")?h=!1:a.append(f('<div class="stripe"></div>').css({opacity:"0",left:F*c+"px",width:J+
"px",height:"0px",background:'url("'+e.current_imgInside.attr("src")+'") '+-1*c*F+"px 0%"})):h=!1,h||(mleft=-1*F*c,a.append(f('<div class="stripe"><img src="'+e.current_imgInside.attr("src")+'" width="'+a.width()+'" height="'+a.height()+'" style="margin-left:'+mleft+'px;"></div>').css({opacity:"0",left:F*c+"px",width:J+"px",height:"0px"})));b.responsive&&h&&(-1==k||-1!=k&&9<=k)&&f(".stripe",a).css({"-webkit-background-size":a.width()+"px "+a.height()+"px","-moz-background-size":a.width()+"px "+a.height()+
"px","-o-background-size":a.width()+"px "+a.height()+"px","-ms-background-size":a.width()+"px "+a.height()+"px","background-size":a.width()+"px "+a.height()+"px"})}function Y(a,b,e){var k=G();f(".stripe",a).remove();f(".block",a).remove();for(var h=Math.round(a.width()/b.numberOfColumns),c=Math.round(a.height()/b.numberOfRows),t,C,y,u,v=!0,q=0;q<b.numberOfRows;q++)for(var l=0;l<b.numberOfColumns;l++)y=h*l,u=c*q,t=l==b.numberOfColumns-1?a.width()-h*(b.numberOfColumns-1):h,C=q==b.numberOfRows-1?a.height()-
c*(b.numberOfRows-1):c,!b.responsive||-1==k||-1!=k&&9<=k?-1!=w.indexOf("ipad")||-1!=w.indexOf("iphone")||-1!=w.indexOf("ipod")||-1!=w.indexOf("webos")?v=!1:a.append(f('<div class="block"></div>').css({opacity:"0",left:y+"px",top:u+"px",width:t+"px",height:C+"px",background:'url("'+e.current_imgInside.attr("src")+'") -'+y+"px -"+u+"px"})):v=!1,v||(mleft=-1*y,mtop=-1*u,a.append(f('<div class="block"><img src="'+e.current_imgInside.attr("src")+'" width="'+a.width()+'" height="'+a.height()+'" style="margin-left:'+
mleft+"px; margin-top:"+mtop+'px;"></div>').css({opacity:"0",left:y+"px",top:u+"px",width:t+"px",height:C+"px"})));b.responsive&&v&&(-1==k||-1!=k&&9<=k)&&f(".block",a).css({"-webkit-background-size":a.width()+"px "+a.height()+"px","-moz-background-size":a.width()+"px "+a.height()+"px","-o-background-size":a.width()+"px "+a.height()+"px","-ms-background-size":a.width()+"px "+a.height()+"px","background-size":a.width()+"px "+a.height()+"px"})}function O(a,b,e,k,h){var c=a.width(),t=a.height();a.css({width:"0"});
a.css({height:"0"});b==k.numberOfRows-1&&e==k.numberOfColumns-1?setTimeout(function(){a.animate({opacity:"1.0",width:c,height:t},1E3*k.effectDuration/3,"",function(){h.trigger("effectComplete")})},x):setTimeout(function(){a.animate({opacity:"1.0",width:c,height:t},1E3*k.effectDuration/3)},x);x+=25}function E(a,b,e,k,h,c,t,C,y,u){var v=!0;if(!e.loop&&b.current_img_no+a>=k||!e.loop&&0>b.current_img_no+a)v=!1;if(v){f(".newFS",c).contents().unwrap();b.arcInitialTime=(new Date).getTime();b.timeElapsed=
0;e.showCircleTimer&&(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=e.behindCircleAlpha/100,b.ctx.arc(e.circleRadius+2*e.circleLineWidth,e.circleRadius+2*e.circleLineWidth,e.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=e.circleLineWidth+2,b.ctx.strokeStyle=e.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=e.circleAlpha/100,b.ctx.arc(e.circleRadius+2*e.circleLineWidth,e.circleRadius+2*e.circleLineWidth,e.circleRadius,0,0,!1),b.ctx.lineWidth=
e.circleLineWidth,b.ctx.strokeStyle=e.circleColor,b.ctx.stroke());f(b.currentImg.attr("data-text-id")).css("display","none");f(h[b.current_img_no]).removeClass("thumbsHolder_ThumbON");e.randomizeImages&&!b.bottomNavClicked?(v=Math.floor(Math.random()*k),b.current_img_no=b.current_img_no===v?Math.floor(Math.random()*k):v):b.current_img_no=b.current_img_no+a>=k?0:0>b.current_img_no+a?k-1:b.current_img_no+a;b.bottomNavClicked=!1;f(h[b.current_img_no]).addClass("thumbsHolder_ThumbON");L(0,t,k,C,e,b,y);
b.currentImg=f(u[b.current_img_no]);b.current_imgInside=b.currentImg.find("img:first");b.currentImg.attr("data-transition")?(current_effect=b.currentImg.attr("data-transition"),"random"==current_effect&&(current_effect=M[Math.floor(Math.random()*M.length)])):current_effect="random"!=e.defaultEffect?e.defaultEffect:M[Math.floor(Math.random()*M.length)];"alternateSlide"==current_effect&&(current_effect=1===a?"slideFromRight":"slideFromLeft");b.effectIsRunning=!0;if("fade"==current_effect||"slideFromLeft"==
current_effect||"slideFromRight"==current_effect||"slideFromTop"==current_effect||"slideFromBottom"==current_effect)S(c,e,b),a=f(".stripe:first",c),"fade"==current_effect&&(a.css({top:"0px",height:"100%",width:c.width()+"px"}),a.animate({opacity:"1.0"},2E3*e.effectDuration,"",function(){c.trigger("effectComplete")})),"slideFromLeft"==current_effect&&(a.css({top:"0px",height:"100%",width:"0"}),a.animate({opacity:"1.0",width:c.width()+"px"},1E3*e.effectDuration,"",function(){c.trigger("effectComplete")})),
"slideFromRight"==current_effect&&(a.css({top:"0px",height:"100%",width:"0",left:c.width()+5+"px"}),a.animate({opacity:"1.0",left:"0",width:c.width()+"px"},1E3*e.effectDuration,"",function(){c.trigger("effectComplete")})),"slideFromTop"==current_effect&&(a.css({top:"0px",height:"0",width:c.width()+"px"}),a.animate({opacity:"1.0",height:c.height()+"px"},1E3*e.effectDuration,"",function(){c.trigger("effectComplete")})),"slideFromBottom"==current_effect&&(a.css({height:"0",width:c.width()+"px",top:c.height()+
"px"}),a.animate({opacity:"1.0",top:0,height:c.height()+"px"},1E3*e.effectDuration,"",function(){c.trigger("effectComplete")}));0<=current_effect.indexOf("Stripes")&&(S(c,e,b),a=0<=current_effect.indexOf("Reverse")?f(".stripe",c).myReverse():f(".stripe",c),x=100,i=0,a.each(function(){var n=f(this);"topBottomDroppingStripes"!=current_effect&&"topBottomDroppingReverseStripes"!=current_effect||n.css({top:"0px"});"bottomTopDroppingStripes"!=current_effect&&"bottomTopDroppingReverseStripes"!=current_effect||
n.css({bottom:"0px"});"leftRightFadingStripes"!=current_effect&&"leftRightFadingReverseStripes"!=current_effect||n.css({top:"0px",height:"100%",width:"0"});"asynchronousDroppingStripes"==current_effect&&(i%2?n.css({top:"0px"}):n.css({bottom:"0px"}));if("leftRightFadingStripes"==current_effect||"leftRightFadingReverseStripes"==current_effect){var r=F;if("leftRightFadingStripes"==current_effect&&i==e.numberOfStripes-1||"leftRightFadingReverseStripes"==current_effect&&0==i)r=J;i==e.numberOfStripes-1?
setTimeout(function(){n.animate({width:r+"px",opacity:"1.0"},800*e.effectDuration,"",function(){c.trigger("effectComplete")})},x):setTimeout(function(){n.animate({width:r+"px",opacity:"1.0"},800*e.effectDuration)},x)}else i==e.numberOfStripes-1?setTimeout(function(){n.animate({height:"100%",opacity:"1.0"},1E3*e.effectDuration,"",function(){c.trigger("effectComplete")})},x):setTimeout(function(){n.animate({height:"100%",opacity:"1.0"},1E3*e.effectDuration)},x);x+=50;i++}));if(0<=current_effect.indexOf("Blocks"))if(Y(c,
e,b),b=0<=current_effect.indexOf("Reverse")?f(".block",c).myReverse():"randomBlocks"==current_effect?X(f(".block",c)):f(".block",c),x=100,"randomBlocks"==current_effect){i=0;var q=e.numberOfRows*e.numberOfColumns;b.each(function(){var n=f(this),r=n.width(),H=n.height();n.css({width:"0",height:"0"});i==q-1?setTimeout(function(){n.animate({opacity:"1.0",width:r,height:H},1E3*e.effectDuration/3,"",function(){c.trigger("effectComplete")})},x):setTimeout(function(){n.animate({opacity:"1.0",width:r,height:H},
1E3*e.effectDuration/3)},x);x+=25;i++})}else{var l=0,m=0,d=[];d[l]=[];b.each(function(){d[l][m]=f(this);m++;m==e.numberOfColumns&&(l++,m=0,d[l]=[])});m=l=0;x=100;b=f(d[l][m]);for(O(b,0,0,e,c);l<e.numberOfRows-1||m<e.numberOfColumns-1;)for(l<e.numberOfRows-1&&l++,m<e.numberOfColumns-1&&m++,i=l,m<l&&e.numberOfRows>e.numberOfColumns&&(i=l-m),j=0,l<m&&e.numberOfRows<e.numberOfColumns&&(j=m-l);0<=i&&j<=m;)b=f(d[i--][j++]),O(b,i,j,e,c);x=e.numberOfRows<e.numberOfColumns?x-25*(e.numberOfRows-1):x-25*(e.numberOfColumns-
1);limit_i=0;for(limit_j=m-l;limit_i<l&&limit_j<m;){i=l+1;for(j=limit_j;i>limit_i&&j<m;)--i,j+=1,b=f(d[i][j]),O(b,i,j,e,c);limit_i++;limit_j++}}}}function L(a,b,e,k,h,c,t){e>h.numberOfThumbsPerScreen&&(e=(b.height()+c.thumbMarginTop)*(e-h.numberOfThumbsPerScreen),k.stop(!0,!0),a&&!c.isCarouselScrolling?(c.isCarouselScrolling=!0,1>=a&&(a=0),k.animate({top:parseInt(h.borderWidth/(h.origWidth/h.width)+e*(a-100)/100,10)+"px"},1100,"easeOutQuad",function(){c.isCarouselScrolling=!1})):c.isCarouselScrolling||
(c.isCarouselScrolling=!0,k.css("opacity","0.5"),a=parseInt(h.borderWidth/(h.origWidth/h.width)-(b.height()+c.thumbMarginTop)*c.current_img_no,10),Math.abs(a)>e&&(a=h.borderWidth/(h.origWidth/h.width)-e),t.slider("value",100+parseInt(100*a/e,10)),k.animate({opacity:1,top:a+"px"},500,"easeOutCubic",function(){c.isCarouselScrolling=!1})))}function T(a,b,e,k,h,c,t,C,y,u,v,q){h.css({height:parseInt(b.origThumbH/(b.origWidth/b.width),10)+"px"});u.css({"padding-left":parseInt(b.origthumbLeftPadding/(b.origWidth/
b.width),10)+"px","padding-right":parseInt(b.origthumbRightPadding/(b.origWidth/b.width),10)+"px","padding-top":parseInt(b.origthumbTopPadding/(b.origWidth/b.width),10)+"px","padding-bottom":parseInt(b.origthumbBottomPadding/(b.origWidth/b.width),10)+"px"});e="px";-1!=v.css("font-size").lastIndexOf("em")&&(e="em");h="px";-1!=v.css("line-height").lastIndexOf("em")&&(h="em");v.css({"font-size":parseInt(b.origthumbTitleFont/(b.origWidth/b.width),10)+e,"line-height":parseInt(b.origthumbTitleLineHeight/
(b.origWidth/b.width),10)+h});e="px";-1!=q.css("font-size").lastIndexOf("em")&&(e="em");h="px";-1!=q.css("line-height").lastIndexOf("em")&&(h="em");q.css({"font-size":parseInt(b.origthumbRegFont/(b.origWidth/b.width),10)+e,"line-height":parseInt(b.origthumbRegLineHeight/(b.origWidth/b.width),10)+h});b.showThumbs&&f(".thumbsHolder_ThumbOFF",k).find("img:first").css({width:parseInt(b.origThumbImgW/(b.origWidth/b.width),10)+"px",height:parseInt(b.origThumbImgH/(b.origWidth/b.width),10)+"px"});a.thumbMarginTop=
Math.floor((y.height()-t.height()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1));thumb_i=0;c.children().each(function(){thumb_i++;theThumb=f(this);1>=thumb_i?theThumb.css("margin-top",Math.floor((y.height()-2*b.borderWidth/(b.origWidth/b.width)-(a.thumbMarginTop+theThumb.height())*(b.numberOfThumbsPerScreen-1)-theThumb.height())/2)+"px"):theThumb.css("margin-top",a.thumbMarginTop+"px")})}function G(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&
(a=parseFloat(RegExp.$1));return parseInt(a,10)}var M="fade slideFromLeft slideFromRight slideFromTop slideFromBottom topBottomDroppingStripes topBottomDroppingReverseStripes bottomTopDroppingStripes bottomTopDroppingReverseStripes asynchronousDroppingStripes leftRightFadingStripes leftRightFadingReverseStripes topBottomDiagonalBlocks topBottomDiagonalReverseBlocks alternateSlide randomBlocks".split(" "),F,J,x=100,w=navigator.userAgent.toLowerCase();f.fn.allinone_bannerWithPlaylist=function(a){a=
f.extend({},f.fn.allinone_bannerWithPlaylist.defaults,a);return this.each(function(){var b=f(this);responsiveWidth=b.parent().width();responsiveHeight=b.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=f(window).width(),responsiveHeight=f(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||
a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));a.width=parseInt(a.width,10);a.height=parseInt(a.height,10);b.css("display","block");var e=f("<div></div>").addClass("allinone_bannerWithPlaylistBorder"),k=f("<div></div>").addClass("allinone_bannerWithPlaylist").addClass(a.skin),h=f('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>  <div class="slider-vertical"></div>     </div>  <canvas class="mycanvas"></canvas>');
b.wrap(k);b.after(h);a.showAllControllers||h.css("display","none");var c=b.parent(".allinone_bannerWithPlaylist");h=f(".bannerControls",c);c.wrap(e);var t=c.parent(".allinone_bannerWithPlaylistBorder"),C=f(".leftNav",c),y=f(".rightNav",c);C.css("display","none");y.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(C.css("display","block"),y.css("display","block"));var u=f(".thumbsHolderWrapper",c),v=f(".thumbsHolderVisibleWrapper",c),q=f(".thumbsHolder",c),l=f(".slider-vertical",c);e=
G();var m=0,d={current_img_no:0,currentImg:0,current_imgInside:"",windowWidth:0,carouselStep:0,thumbMarginTop:0,bottomNavClicked:!1,effectIsRunning:!1,mouseOverBanner:!1,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,canvas:"",ctx:"",bannerRatio:a.origWidth/a.origHeight};d.canvas=f(".mycanvas",c)[0];d.canvas.width=2*a.circleRadius+4*a.circleLineWidth;d.canvas.height=2*a.circleRadius+4*a.circleLineWidth;-1!=e&&9>e&&(a.showCircleTimer=!1);a.showCircleTimer&&(d.ctx=d.canvas.getContext("2d"));
t.width(a.width);t.height(a.height);t.css("background",a.borderColor);c.width(a.width-3*a.borderWidth/(a.origWidth/a.width)-a.playlistWidth/(a.origWidth/a.width));c.height(a.height-2*a.borderWidth/(a.origWidth/a.width));c.css({left:a.borderWidth/(a.origWidth/a.width)+"px",top:a.borderWidth/(a.origWidth/a.width)+"px"});h.width("100%");h.height("100%");v.width(a.playlistWidth/(a.origWidth/a.width));v.height(c.height());u.width(a.playlistWidth/(a.origWidth/a.width));u.height(c.height());u.css({top:0,
right:-1*(a.borderWidth/(a.origWidth/a.width)+a.playlistWidth/(a.origWidth/a.width))+"px"});q.width(a.playlistWidth/(a.origWidth/a.width));q.css("top",a.borderWidth/(a.origWidth/a.width)+"px");a.centerPlugin&&t.css({margin:"0 auto"});var n=b.find("ul:first").children(),r,H="";k=0;n.each(function(){d.currentImg=f(this);d.currentImg.is("li")||(d.currentImg=d.currentImg.find("li:first"));if(d.currentImg.is("li")){d.currentImg.css("display","none");m++;var p=f(n[m-1]).attr("data-bottom-thumb");H="";a.showThumbs&&
(H='<img src="'+p+'">');r=f('<div class="thumbsHolder_ThumbOFF" rel="'+(m-1)+'"><div class="padding">'+H+'<span class="title">'+d.currentImg.attr("data-title")+'</span><span class="reg">'+d.currentImg.attr("data-desc")+"</span></div></div>");q.append(r);0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor(a.origHeight/r.height())),a.origThumbW=r.width(),a.origThumbH=r.height(),D=f(".thumbsHolder_ThumbOFF .padding",c),a.origthumbLeftPadding=D.css("padding-left").substr(0,
D.css("padding-left").lastIndexOf("px")),a.origthumbRightPadding=D.css("padding-right").substr(0,D.css("padding-left").lastIndexOf("px")),a.origthumbTopPadding=D.css("padding-top").substr(0,D.css("padding-left").lastIndexOf("px")),a.origthumbBottomPadding=D.css("padding-bottom").substr(0,D.css("padding-left").lastIndexOf("px")),d.thumbMarginTop=Math.floor((u.height()-r.height()*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-1)),z=f(".thumbsHolder_ThumbOFF .title",c),A=f(".thumbsHolder_ThumbOFF .reg",
c),-1!=z.css("font-size").lastIndexOf("px")?a.origthumbTitleFont=z.css("font-size").substr(0,z.css("font-size").lastIndexOf("px")):-1!=z.css("font-size").lastIndexOf("em")&&(a.origthumbTitleFont=z.css("font-size").substr(0,z.css("font-size").lastIndexOf("em"))),-1!=z.css("line-height").lastIndexOf("px")?a.origthumbTitleLineHeight=z.css("line-height").substr(0,z.css("line-height").lastIndexOf("px")):-1!=z.css("line-height").lastIndexOf("em")&&(a.origthumbTitleLineHeight=z.css("line-height").substr(0,
z.css("line-height").lastIndexOf("em"))),-1!=A.css("font-size").lastIndexOf("px")?a.origthumbRegFont=A.css("font-size").substr(0,A.css("font-size").lastIndexOf("px")):-1!=A.css("font-size").lastIndexOf("em")&&(a.origthumbRegFont=A.css("font-size").substr(0,A.css("font-size").lastIndexOf("em"))),-1!=A.css("line-height").lastIndexOf("px")?a.origthumbRegLineHeight=A.css("line-height").substr(0,A.css("line-height").lastIndexOf("px")):-1!=A.css("line-height").lastIndexOf("em")&&(a.origthumbRegLineHeight=
A.css("line-height").substr(0,A.css("line-height").lastIndexOf("em"))));q.css("height",q.height()+d.thumbMarginTop+r.height()+"px");1>=m?r.css("margin-top",Math.floor((u.height()-2*a.borderWidth/(a.origWidth/a.width)-(d.thumbMarginTop+r.height())*(a.numberOfThumbsPerScreen-1)-r.height())/2)+"px"):r.css("margin-top",d.thumbMarginTop+"px")}});var D=f(".thumbsHolder_ThumbOFF .padding",c);var z=f(".thumbsHolder_ThumbOFF .title",c);var A=f(".thumbsHolder_ThumbOFF .reg",c);var B=f(".thumbsHolder_ThumbOFF",
c);T(d,a,m,c,B,q,r,v,u,D,z,A);m>a.numberOfThumbsPerScreen&&(l.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(p,g){L(g.value,r,m,q,a,d,l)}}),0>=a.borderWidth&&(k=l.width()/2),l.height(u.height()-25),l.css({display:"block",left:Math.floor(a.width-2*a.borderWidth/(a.origWidth/a.width)+(a.borderWidth/(a.origWidth/a.width)-l.width())/2)-k+"px"}));d.current_img_no=a.firstImg;a.firstImg>m&&(d.current_img_no=m);0>a.firstImg&&(d.current_img_no=0);a.randomizeImages&&
(d.current_img_no=Math.floor(Math.random()*m));d.current_img_no>=a.numberOfThumbsPerScreen&&L(0,r,m,q,a,d,l);d.currentImg=f(n[d.current_img_no]);d.current_imgInside=d.currentImg.find("img:first");-1!=w.indexOf("ipad")||-1!=w.indexOf("iphone")||-1!=w.indexOf("ipod")||-1!=w.indexOf("webos")||-1!=e&&7>=e?c.append('<img id="curBgImgIos" src="'+d.current_imgInside.attr("src")+'" width="'+c.width()+'" height="'+c.height()+'">'):(c.css("background",'url("'+d.current_imgInside.attr("src")+'") no-repeat'),
a.responsive&&(-1==e||-1!=e&&9<=e?c.css({"-webkit-background-size":c.width()+"px "+c.height()+"px","-moz-background-size":c.width()+"px "+c.height()+"px","-o-background-size":c.width()+"px "+c.height()+"px","-ms-background-size":c.width()+"px "+c.height()+"px","background-size":c.width()+"px "+c.height()+"px"}):8==e&&c.css({filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+d.current_imgInside.attr("src")+"',sizingMethod='scale')"})));a.enableTouchScreen&&c.swipe({swipe:function(p,
g,K,N,U){d.effectIsRunning||E("right"==g?-1:1,d,a,m,B,c,r,q,l,n)}});Q(d,a,b,h);c.bind("effectComplete",function(){var p=G();d.effectIsRunning=!1;-1!=w.indexOf("ipad")||-1!=w.indexOf("iphone")||-1!=w.indexOf("ipod")||-1!=w.indexOf("webos")||-1!=p&&7>=p?(f("#curBgImgIos",c).attr("src",d.current_imgInside.attr("src")),f("#curBgImgIos",c).width(c.width()),f("#curBgImgIos",c).height(c.height())):(c.css("background",'url("'+d.current_imgInside.attr("src")+'") no-repeat'),a.responsive&&(-1==p||-1!=p&&9<=
p?c.css({"-webkit-background-size":c.width()+"px "+c.height()+"px","-moz-background-size":c.width()+"px "+c.height()+"px","-o-background-size":c.width()+"px "+c.height()+"px","-ms-background-size":c.width()+"px "+c.height()+"px","background-size":c.width()+"px "+c.height()+"px"}):8==p&&c.css({filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+d.current_imgInside.attr("src")+"',sizingMethod='scale')"})));d.arcInitialTime=(new Date).getTime();d.timeElapsed=0;a.showCircleTimer&&(clearInterval(d.intervalID),
d.ctx.clearRect(0,0,d.canvas.width,d.canvas.height),d.ctx.beginPath(),d.ctx.globalAlpha=a.behindCircleAlpha/100,d.ctx.arc(a.circleRadius+2*a.circleLineWidth,a.circleRadius+2*a.circleLineWidth,a.circleRadius,0,2*Math.PI,!1),d.ctx.lineWidth=a.circleLineWidth+2,d.ctx.strokeStyle=a.behindCircleColor,d.ctx.stroke(),d.ctx.beginPath(),d.ctx.globalAlpha=a.circleAlpha/100,d.ctx.arc(a.circleRadius+2*a.circleLineWidth,a.circleRadius+2*a.circleLineWidth,a.circleRadius,0,0,!1),d.ctx.lineWidth=a.circleLineWidth,
d.ctx.strokeStyle=a.circleColor,d.ctx.stroke(),d.intervalID=setInterval(function(){R(d,a)},125));Q(d,a,b,h);0<a.autoPlay&&1<m&&!d.mouseOverBanner&&(clearTimeout(d.timeoutID),d.timeoutID=setTimeout(function(){E(1,d,a,m,B,c,r,q,l,n)},1E3*a.autoPlay))});c.on("mouseenter",function(){d.mouseOverBanner=!0;clearTimeout(d.timeoutID);nowx=(new Date).getTime();d.timeElapsed+=nowx-d.arcInitialTime;a.autoHideNavArrows&&a.showNavArrows&&(C.css("display","block"),y.css("display","block"))});c.on("mouseleave",function(){d.mouseOverBanner=
!1;nowx=(new Date).getTime();a.autoHideNavArrows&&a.showNavArrows&&(C.css("display","none"),y.css("display","none"));if(0<a.autoPlay&&1<m){clearTimeout(d.timeoutID);d.arcInitialTime=(new Date).getTime();var p=parseInt(1E3*a.autoPlay-(d.timeElapsed+nowx-d.arcInitialTime),10);d.timeoutID=setTimeout(function(){E(1,d,a,m,B,c,r,q,l,n)},p)}});c.on("click",function(){if(void 0!=f(n[d.current_img_no]).attr("data-link")&&""!=f(n[d.current_img_no]).attr("data-link")&&!d.effectIsRunning){var p=a.target;void 0!=
f(n[d.current_img_no]).attr("data-target")&&""!=f(n[d.current_img_no]).attr("data-target")&&(p=f(n[d.current_img_no]).attr("data-target"));"_blank"==p?window.open(f(n[d.current_img_no]).attr("data-link")):window.location=f(n[d.current_img_no]).attr("data-link")}});C.on("click",function(){d.effectIsRunning||(clearTimeout(d.timeoutID),E(-1,d,a,m,B,c,r,q,l,n))});y.on("click",function(){d.effectIsRunning||(clearTimeout(d.timeoutID),E(1,d,a,m,B,c,r,q,l,n))});B.on("click",function(){if(!d.effectIsRunning){var p=
f(this).attr("rel");f(B[d.current_img_no]).removeClass("thumbsHolder_ThumbON");d.bottomNavClicked=!0;d.current_img_no=p-1;E(1,d,a,m,B,c,r,q,l,n)}});B.on("mouseenter",function(){var p=f(this);p.attr("rel");p.addClass("thumbsHolder_ThumbON")});B.on("mouseleave",function(){var p=f(this),g=p.attr("rel");d.current_img_no!=g&&p.removeClass("thumbsHolder_ThumbON")});v.mousewheel(function(p,g,K,N){m>a.numberOfThumbsPerScreen&&(p.preventDefault(),p=l.slider("value"),1<parseInt(p,10)&&-1==parseInt(g,10)||100>
parseInt(p,10)&&1==parseInt(g,10))&&(p+=g,l.slider("value",p),L(p,r,m,q,a,d,l))});var P=!1;f(window).on("resize",function(){var p=G();doResizeNow=!0;-1!=navigator.userAgent.indexOf("Android")&&(0==a.windowOrientationScreenSize0&&0==window.orientation&&(a.windowOrientationScreenSize0=f(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=f(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=
f(window).height()),a.windowOrientationScreenSize0&&0==window.orientation&&f(window).width()>a.windowOrientationScreenSize0&&(doResizeNow=!1),a.windowOrientationScreenSize90&&90==window.orientation&&f(window).height()>a.windowOrientationScreenSize90&&(doResizeNow=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&f(window).height()>a.windowOrientationScreenSize_90&&(doResizeNow=!1),0==d.windowWidth&&(doResizeNow=!1,d.windowWidth=f(window).width()));-1!=p&&9==p&&0==d.windowWidth&&(doResizeNow=
!1);d.windowWidth==f(window).width()?(doResizeNow=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):d.windowWidth=f(window).width();a.responsive&&doResizeNow&&(!1!==P&&clearTimeout(P),P=setTimeout(function(){var g=a,K=m,N=r,U=D,Z=z,aa=A,I=G(),V=0;responsiveWidth=b.parent().parent().parent().width();responsiveHeight=b.parent().parent().parent().height();g.responsiveRelativeToBrowser&&(responsiveWidth=
f(window).width(),responsiveHeight=f(window).height());g.width100Proc&&(g.width=responsiveWidth);g.height100Proc&&(g.height=responsiveHeight);if(g.origWidth!=responsiveWidth||g.width100Proc)g.origWidth>responsiveWidth||g.width100Proc?g.width=responsiveWidth:g.width100Proc||(g.width=g.origWidth),g.height100Proc||(g.height=g.width/d.bannerRatio),g.width=parseInt(g.width,10),g.height=parseInt(g.height,10),t.width(g.width),t.height(g.height),c.width(parseInt(g.width-3*g.borderWidth/(g.origWidth/g.width)-
g.playlistWidth/(g.origWidth/g.width),10)),c.height(parseInt(g.height-2*g.borderWidth/(g.origWidth/g.width),10)),c.css({left:g.borderWidth/(g.origWidth/g.width)+"px",top:g.borderWidth/(g.origWidth/g.width)+"px"}),v.width(g.playlistWidth/(g.origWidth/g.width)),v.height(c.height()),u.width(g.playlistWidth/(g.origWidth/g.width)),u.height(c.height()),u.css({top:0,right:-1*(g.borderWidth/(g.origWidth/g.width)+g.playlistWidth/(g.origWidth/g.width))+"px"}),q.width(g.playlistWidth/(g.origWidth/g.width)),
q.css("top",g.borderWidth/(g.origWidth/g.width)+"px"),K>g.numberOfThumbsPerScreen&&(0>=g.borderWidth&&(V=l.width()/2),l.height(u.height()-25),l.css({display:"block",left:Math.floor(g.width-2*g.borderWidth/(g.origWidth/g.width)+(g.borderWidth/(g.origWidth/g.width)-l.width())/2)-V+"px"})),-1!=w.indexOf("ipad")||-1!=w.indexOf("iphone")||-1!=w.indexOf("ipod")||-1!=w.indexOf("webos")||-1!=I&&7>=I?(f("#curBgImgIos",c).attr("src",d.current_imgInside.attr("src")),f("#curBgImgIos",c).width(c.width()),f("#curBgImgIos",
c).height(c.height())):-1==I||-1!=I&&9<=I?c.css({"-webkit-background-size":c.width()+"px "+c.height()+"px","-moz-background-size":c.width()+"px "+c.height()+"px","-o-background-size":c.width()+"px "+c.height()+"px","-ms-background-size":c.width()+"px "+c.height()+"px","background-size":c.width()+"px "+c.height()+"px"}):8==I&&c.css({filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+d.current_imgInside.attr("src")+"',sizingMethod='scale')"}),T(d,g,K,c,B,q,N,v,u,U,Z,aa),clearTimeout(d.timeoutID),
E(1,d,g,K,B,c,N,q,l,n)},300))});f(B[d.current_img_no]).addClass("thumbsHolder_ThumbON");0<a.autoPlay&&1<m&&(a.showCircleTimer&&(d.intervalID=setInterval(function(){R(d,a)},125)),d.timeoutID=setTimeout(function(){E(1,d,a,m,B,c,r,q,l,n)},1E3*a.autoPlay))})};f.fn.myReverse=[].reverse;f.fn.allinone_bannerWithPlaylist.defaults={skin:"elegant",width:960,height:384,width100Proc:!1,height100Proc:!1,randomizeImages:!1,firstImg:0,numberOfStripes:20,numberOfRows:5,numberOfColumns:10,defaultEffect:"random",effectDuration:.5,
autoPlay:4,loop:!0,target:"_blank",showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showThumbs:!0,borderWidth:15,borderColor:"#e9e9e9",playlistWidth:300,enableTouchScreen:!0,absUrl:"",showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:50,responsive:!1,responsiveRelativeToBrowser:!0,centerPlugin:!1,numberOfThumbsPerScreen:0,origWidth:0,origHeight:0,origThumbW:0,
origThumbH:0,origThumbImgW:214,origThumbImgH:128,origthumbLeftPadding:0,origthumbRightPadding:0,origthumbTopPadding:0,origthumbBottomPadding:0,origthumbTitleFont:0,origthumbRegFont:0,origthumbTitleLineHeight:0,origthumbRegLineHeight:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
